package com.wontlost.web3.x402.facilitator;

public enum FacilitatorFailure { UNAVAILABLE, TIMEOUT, RATE_LIMITED, AUTHENTICATION, REJECTED, MALFORMED_RESPONSE, RESPONSE_TOO_LARGE, SETTLEMENT_UNKNOWN, INTERNAL }
